- name: geerlingguy.docker
  src: https://github.com/geerlingguy/ansible-role-docker.git
  version: master

- name: geerlingguy.pip
  src: https://github.com/geerlingguy/ansible-role-pip.git
  version: master

- name: geerlingguy.kubernetes
  src: https://github.com/geerlingguy/ansible-role-kubernetes.git
  version: master

- name: geerlingguy.swap
  src: https://github.com/geerlingguy/ansible-role-swap.git
  version: master

- name: geerlingguy.firewall
  src: https://github.com/geerlingguy/ansible-role-firewall.git
  version: master