- name: geerlingguy.docker
  src: https://github.com/geerlingguy/ansible-role-docker.git
  version: master

- name: geerlingguy.pip
  src: https://github.com/geerlingguy/ansible-role-pip.git
  version: master

- name: geerlingguy.kubernetes
  src: https://github.com/geerlingguy/ansible-role-kubernetes.git
  version: master
