---
- name: Install common packages
  hosts: all
  become: yes
  tags: setup_packages

  vars:
    pip_install_packages:
      - name: docker
      - name: pyopenssl
    docker_install_compose: no
    docker_edition: 'ce'

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

- name: Install kubernetes master
  hosts: all
  become: yes
  tags: setup_packages

  vars:
    kubernetes_version: '1.14'
    kubernetes_allow_pods_on_master: yes
    kubernetes_apiserver_advertise_address: "{{ inventory_hostname }}"
    kubernetes_enable_web_ui: yes'

  roles:
    - geerlingguy.kubernetes
