---
- name: "Ensure default users are installed and have public keys available"
  hosts: all
  become: yes
  tags: setup_users
  tasks:
    - name: "Ensure wheel group exists"
      group:
        name: "wheel"

    - name: "Ensure that the wheel group is able to use sudo"
      lineinfile:
        path: /etc/sudoers
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL:ALL) ALL'
        validate: 'visudo -cf %s'

    - name: "Ensure default groups are setup"
      group:
        name: "{{ item.name }}"
        state: present
        system: "{{ item.system }}"
        gid: "{{ item.gid }}"
      with_items: "{{ default_groups }}"

    - name: "Ensure default users are setup"
      user:
        group: "{{ item.group  }}"
        name: "{{ item.username }}"
        groups: "{{ item.groups }}"
        comment: "{{ item.comment }}"
        create_home: "{{ item.create_home }}"
        password: "{{ item.password }}"
        shell: "{{ item.shell }}"
        uid: "{{ item.uid }}"
      with_items: "{{ default_users }}"

    - name: "Add public key to authorized_keys"
      authorized_key:
        user: "{{ item.username }}"
        state: present
        key: "{{ item.authorized_key }}"
      with_items: "{{ default_users }}"