---
- name: Install common packages
  hosts: all
  become: yes
  tags: setup_packages

  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
      - name: pyopenssl
    docker_install_compose: true
    docker_compose_version: 1.17.1
    docker_edition: 'ce'

    firewall_allowed_tcp_ports:
      - 22
      - 80
      - 443

  roles:
    - geerlingguy.firewall
    - geerlingguy.pip
    - geerlingguy.docker
    - geerlingguy.certbot