---
- name: Install common packages
  hosts: all
  become: yes
  tags: setup_packages

  vars:
    pip_install_packages:
      - name: docker
      - name: pyopenssl
    docker_install_compose: no
    docker_edition: 'ce'

    firewall_allowed_tcp_ports:
      - 22
      - 80
      - 443

  roles:
    - geerlingguy.firewall
    - geerlingguy.pip
    - geerlingguy.docker
    - geerlingguy.swap

- name: Install kubernetes
  hosts: all
  become: yes
  tags: setup_packages

  vars:
    kubernetes_version: '1.14'
    kubernetes_allow_pods_on_master: yes
    kubernetes_enable_web_ui: yes

  roles:
    - geerlingguy.kubernetes
