---
- name: "Ensure default users are installed and have public keys available"
  hosts: all
  become: yes
  tags: setup_users
  tasks:
    - name: "Ensure default groups are set up"
      group:
        name: "{{ item.name }}"
        state: present
        system: "{{ item.system }}"
        gid: "{{ item.gid }}"
      with_items: "{{ default_groups }}"

    - name: "Ensure default users are set up"
      user:
        group: "{{ item.group  }}"
        name: "{{ item.username }}"
        groups: "{{ item.groups }}"
        comment: "{{ item.comment }}"
        create_home: "{{ item.create_home }}"
        password: "{{ item.password }}"
        shell: "{{ item.shell }}"
        uid: "{{ item.uid }}"
      with_items: "{{ default_users }}"

    - name: "Ensure that sudogroups have sudo permission"
      lineinfile:
        path: /etc/sudoers
        regexp: '^%{{ item }}'
        line: '%{{ item }} ALL=(ALL:ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
      with_items: "{{ default_sudo_groups }}"

    - name: "Ensure public key(s) are in authorized_keys"
      authorized_key:
        user: "{{ item.username }}"
        state: present
        key: "{{ item.authorized_key }}"
      with_items: "{{ default_users }}"

    - name: "Ensure empty password login is disabled"
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?PermitEmptyPasswords"
        line: "PermitEmptyPasswords no"
      notify: sshd_restart

    - name: "Ensure password login is disabled"
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^(#\\s*)?PasswordAuthentication "
        line: "PasswordAuthentication no"
      notify: sshd_restart

    - name: "Ensure Pam is enabled"
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#?UsePAM"
        line: "UsePAM yes"
      notify: sshd_restart
