---
- hosts: all
  gather_facts: no
  tasks:
    - name: Ensure python
      raw: sudo apt update && sudo apt -y install python

- hosts: develop
  roles:
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.kubernetes
    - common
