---
- hosts: all
  gather_facts: no
  tasks:
    - name: Ensure python
      raw: sudo apt update && sudo apt -y install python

- hosts: all
  roles:
    - geerlingguy.docker
    - geerlingguy.certbot
    - geerlingguy.pip
    - common

- hosts: personal-website
  roles:
    - certbot-digitalocean
